2_formatting
romanyx/effective_go pull request #1
Opened 2018-04-07 12:01 UTC by Dipress

2018-04-07 12:57 UTC, romanyx requested changes
Добавил свои предложения по переводу

2018-04-07 12:57 UTC, romanyx commented on md/2_formatting.md
> -Formatting issues are the most contentious but the least consequential. People can adapt to different formatting styles but it's better if they don't have to, and less time is devoted to the topic if
Вопросы форматирования самые спорные, но наименее логически обоснованные. Люди могут адаптироваться к различным стилям форматирования, но лучше когда в этом нет необходимости, и вообще, меньше времени уделяется этой теме когда все вынуждены придерживаться одного и того же стиля. Проблема в том, как приблизиться к этой утопии без длинного предписывающего руководства по стилю.

2018-04-07 12:57 UTC, romanyx commented on md/2_formatting.md
> +C Go мы применяем необычный подход и даем машине позаботиться о большинстве проблемах форматирования. Программа `gofmt` (также доступно как `go fmt` который действует на уровне пакета а не на уровне
Источник я бы заменил на исходник.

2018-04-07 12:57 UTC, romanyx commented on md/2_formatting.md
> +C Go мы применяем необычный подход и даем машине позаботиться о большинстве проблемах форматирования. Программа `gofmt` (также доступно как `go fmt` который действует на уровне пакета а не на уровне
Если вы не знаете как правильно структурировать код при его изменении, запустите gofmt, если ответ кажется неправильным, перестройте свою программу (или сообщите об ошибке `gofmt`), не игнорируйте gofmt.

2018-04-07 15:57 UTC, Dipress commented on md/2_formatting.md
> +C Go мы применяем необычный подход и даем машине позаботиться о большинстве проблемах форматирования. Программа `gofmt` (также доступно как `go fmt` который действует на уровне пакета а не на уровне
Это как я понимаю, относиться к этому фрагменту:
"Если Вы хотите знать как обработать какую-то новую разметку (какой-то новый фрагмент кода), запустите `gofmt`; если ответ кажется неправильным - поправьте свою программу (или файл с ошибкой на который указывает `gofmt`), не работайте в обход ее." ?

2018-04-07 15:57 UTC, Dipress commented on md/2_formatting.md
> +C Go мы применяем необычный подход и даем машине позаботиться о большинстве проблемах форматирования. Программа `gofmt` (также доступно как `go fmt` который действует на уровне пакета а не на уровне
Может вместо "перестройте свою программу" заменить на "поправьте свою программу" ?

2018-04-07 15:58 UTC, romanyx commented on md/2_formatting.md
> +C Go мы применяем необычный подход и даем машине позаботиться о большинстве проблемах форматирования. Программа `gofmt` (также доступно как `go fmt` который действует на уровне пакета а не на уровне
да, так вернее

2018-04-09 08:58 UTC, romanyx approved these changes

2018-04-09 08:58 UTC, merged